## Rest of the file pulled from https://github.com/actions/setup-python/blob/master/.github/workflows/workflow.yml
name: Main workflow
on: [push, pull_request]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-20.04, ubuntu-18.04, windows-2019, windows-2016]
        php: [ '5.6', '7.1', '7.2', '7.3', '7.4', '8.0' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Node.js lts
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    - name: npm install
      run: npm install

    - name: Lint
      if: matrix.operating-system == 'ubuntu-20.04' || matrix.operating-system == 'ubuntu-18.04'
      run: npm run format-check

    - name: npm test
      if: matrix.operating-system == 'ubuntu-20.04' || matrix.operating-system == 'ubuntu-18.04'
      run: npm test

    - name: Setup PHP
      uses: nanasess/setup-php@v3
      with:
        php-version: ${{ matrix.php }}

    - name: Setup composer
      uses: ./

    - name: composer list
      run: |
        composer list

